# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_qtdesigner\tribDesign.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(890, 543)
        MainWindow.setToolTipDuration(2)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 861, 484))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.distributionDefBox = QtWidgets.QGroupBox(self.layoutWidget)
        self.distributionDefBox.setMinimumSize(QtCore.QSize(250, 210))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.distributionDefBox.setFont(font)
        self.distributionDefBox.setObjectName("distributionDefBox")
        self.layoutWidget1 = QtWidgets.QWidget(self.distributionDefBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 30, 231, 161))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBoxDist = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBoxDist.setCurrentText("")
        self.comboBoxDist.setObjectName("comboBoxDist")
        self.verticalLayout.addWidget(self.comboBoxDist)
        self.horizontalLayoutLabel = QtWidgets.QHBoxLayout()
        self.horizontalLayoutLabel.setObjectName("horizontalLayoutLabel")
        self.labelProb = QtWidgets.QLabel(self.layoutWidget1)
        self.labelProb.setMinimumSize(QtCore.QSize(110, 20))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.labelProb.setFont(font)
        self.labelProb.setAlignment(QtCore.Qt.AlignCenter)
        self.labelProb.setObjectName("labelProb")
        self.horizontalLayoutLabel.addWidget(self.labelProb)
        self.labelValue = QtWidgets.QLabel(self.layoutWidget1)
        self.labelValue.setMinimumSize(QtCore.QSize(110, 20))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.labelValue.setFont(font)
        self.labelValue.setAlignment(QtCore.Qt.AlignCenter)
        self.labelValue.setObjectName("labelValue")
        self.horizontalLayoutLabel.addWidget(self.labelValue)
        self.verticalLayout.addLayout(self.horizontalLayoutLabel)
        self.horizontalLayout1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout1.setObjectName("horizontalLayout1")
        self.lineEditProb1 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEditProb1.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEditProb1.setMaxLength(5)
        self.lineEditProb1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditProb1.setClearButtonEnabled(False)
        self.lineEditProb1.setObjectName("lineEditProb1")
        self.horizontalLayout1.addWidget(self.lineEditProb1)
        self.labeldots1 = QtWidgets.QLabel(self.layoutWidget1)
        self.labeldots1.setMinimumSize(QtCore.QSize(10, 45))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.labeldots1.setFont(font)
        self.labeldots1.setAlignment(QtCore.Qt.AlignCenter)
        self.labeldots1.setObjectName("labeldots1")
        self.horizontalLayout1.addWidget(self.labeldots1)
        self.lineEditValue1 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEditValue1.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEditValue1.setMaxLength(10)
        self.lineEditValue1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditValue1.setPlaceholderText("")
        self.lineEditValue1.setClearButtonEnabled(False)
        self.lineEditValue1.setObjectName("lineEditValue1")
        self.horizontalLayout1.addWidget(self.lineEditValue1)
        self.verticalLayout.addLayout(self.horizontalLayout1)
        self.horizontalLayout2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout2.setObjectName("horizontalLayout2")
        self.lineEditProb2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEditProb2.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEditProb2.setMaxLength(5)
        self.lineEditProb2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditProb2.setClearButtonEnabled(False)
        self.lineEditProb2.setObjectName("lineEditProb2")
        self.horizontalLayout2.addWidget(self.lineEditProb2)
        self.labeldots2 = QtWidgets.QLabel(self.layoutWidget1)
        self.labeldots2.setMinimumSize(QtCore.QSize(10, 45))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.labeldots2.setFont(font)
        self.labeldots2.setAlignment(QtCore.Qt.AlignCenter)
        self.labeldots2.setObjectName("labeldots2")
        self.horizontalLayout2.addWidget(self.labeldots2)
        self.lineEditValue2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEditValue2.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEditValue2.setMaxLength(10)
        self.lineEditValue2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditValue2.setPlaceholderText("")
        self.lineEditValue2.setClearButtonEnabled(False)
        self.lineEditValue2.setObjectName("lineEditValue2")
        self.horizontalLayout2.addWidget(self.lineEditValue2)
        self.verticalLayout.addLayout(self.horizontalLayout2)
        self.verticalLayout_3.addWidget(self.distributionDefBox, 0, QtCore.Qt.AlignLeft)
        self.distributionDefBox_2 = QtWidgets.QGroupBox(self.layoutWidget)
        self.distributionDefBox_2.setMinimumSize(QtCore.QSize(250, 250))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.distributionDefBox_2.setFont(font)
        self.distributionDefBox_2.setObjectName("distributionDefBox_2")
        self.layoutWidget2 = QtWidgets.QWidget(self.distributionDefBox_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 30, 231, 208))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout1_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout1_2.setObjectName("horizontalLayout1_2")
        self.labelP90 = QtWidgets.QLabel(self.layoutWidget2)
        self.labelP90.setMinimumSize(QtCore.QSize(35, 45))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.labelP90.setFont(font)
        self.labelP90.setAlignment(QtCore.Qt.AlignCenter)
        self.labelP90.setObjectName("labelP90")
        self.horizontalLayout1_2.addWidget(self.labelP90)
        self.labeldotsP90 = QtWidgets.QLabel(self.layoutWidget2)
        self.labeldotsP90.setMinimumSize(QtCore.QSize(10, 45))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.labeldotsP90.setFont(font)
        self.labeldotsP90.setAlignment(QtCore.Qt.AlignCenter)
        self.labeldotsP90.setObjectName("labeldotsP90")
        self.horizontalLayout1_2.addWidget(self.labeldotsP90)
        self.lineEditP90 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEditP90.setEnabled(False)
        self.lineEditP90.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEditP90.setText("")
        self.lineEditP90.setMaxLength(10)
        self.lineEditP90.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditP90.setPlaceholderText("")
        self.lineEditP90.setClearButtonEnabled(False)
        self.lineEditP90.setObjectName("lineEditP90")
        self.horizontalLayout1_2.addWidget(self.lineEditP90)
        self.verticalLayout_2.addLayout(self.horizontalLayout1_2)
        self.horizontalLayout2_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout2_2.setObjectName("horizontalLayout2_2")
        self.labelP50 = QtWidgets.QLabel(self.layoutWidget2)
        self.labelP50.setMinimumSize(QtCore.QSize(35, 45))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.labelP50.setFont(font)
        self.labelP50.setAlignment(QtCore.Qt.AlignCenter)
        self.labelP50.setObjectName("labelP50")
        self.horizontalLayout2_2.addWidget(self.labelP50)
        self.labeldotsP50 = QtWidgets.QLabel(self.layoutWidget2)
        self.labeldotsP50.setMinimumSize(QtCore.QSize(10, 45))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.labeldotsP50.setFont(font)
        self.labeldotsP50.setAlignment(QtCore.Qt.AlignCenter)
        self.labeldotsP50.setObjectName("labeldotsP50")
        self.horizontalLayout2_2.addWidget(self.labeldotsP50)
        self.lineEditP50 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEditP50.setEnabled(False)
        self.lineEditP50.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEditP50.setText("")
        self.lineEditP50.setMaxLength(10)
        self.lineEditP50.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditP50.setPlaceholderText("")
        self.lineEditP50.setClearButtonEnabled(False)
        self.lineEditP50.setObjectName("lineEditP50")
        self.horizontalLayout2_2.addWidget(self.lineEditP50)
        self.verticalLayout_2.addLayout(self.horizontalLayout2_2)
        self.horizontalLayout2_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout2_3.setObjectName("horizontalLayout2_3")
        self.labelP10 = QtWidgets.QLabel(self.layoutWidget2)
        self.labelP10.setMinimumSize(QtCore.QSize(35, 45))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.labelP10.setFont(font)
        self.labelP10.setAlignment(QtCore.Qt.AlignCenter)
        self.labelP10.setObjectName("labelP10")
        self.horizontalLayout2_3.addWidget(self.labelP10)
        self.labeldotsP10 = QtWidgets.QLabel(self.layoutWidget2)
        self.labeldotsP10.setMinimumSize(QtCore.QSize(10, 45))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.labeldotsP10.setFont(font)
        self.labeldotsP10.setAlignment(QtCore.Qt.AlignCenter)
        self.labeldotsP10.setObjectName("labeldotsP10")
        self.horizontalLayout2_3.addWidget(self.labeldotsP10)
        self.lineEditP10 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEditP10.setEnabled(False)
        self.lineEditP10.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEditP10.setText("")
        self.lineEditP10.setMaxLength(10)
        self.lineEditP10.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditP10.setPlaceholderText("")
        self.lineEditP10.setClearButtonEnabled(False)
        self.lineEditP10.setObjectName("lineEditP10")
        self.horizontalLayout2_3.addWidget(self.lineEditP10)
        self.verticalLayout_2.addLayout(self.horizontalLayout2_3)
        self.horizontalLayout2_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout2_4.setObjectName("horizontalLayout2_4")
        self.lineEditProb2_2 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEditProb2_2.setMinimumSize(QtCore.QSize(50, 30))
        self.lineEditProb2_2.setText("")
        self.lineEditProb2_2.setMaxLength(5)
        self.lineEditProb2_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditProb2_2.setClearButtonEnabled(False)
        self.lineEditProb2_2.setObjectName("lineEditProb2_2")
        self.horizontalLayout2_4.addWidget(self.lineEditProb2_2)
        self.labeldotsP10_2 = QtWidgets.QLabel(self.layoutWidget2)
        self.labeldotsP10_2.setMinimumSize(QtCore.QSize(10, 45))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.labeldotsP10_2.setFont(font)
        self.labeldotsP10_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labeldotsP10_2.setObjectName("labeldotsP10_2")
        self.horizontalLayout2_4.addWidget(self.labeldotsP10_2)
        self.lineEditP10_2 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEditP10_2.setEnabled(False)
        self.lineEditP10_2.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEditP10_2.setText("")
        self.lineEditP10_2.setMaxLength(10)
        self.lineEditP10_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditP10_2.setPlaceholderText("")
        self.lineEditP10_2.setClearButtonEnabled(False)
        self.lineEditP10_2.setObjectName("lineEditP10_2")
        self.horizontalLayout2_4.addWidget(self.lineEditP10_2)
        self.horizontalLayout2_4.setStretch(0, 1)
        self.horizontalLayout2_4.setStretch(2, 6)
        self.verticalLayout_2.addLayout(self.horizontalLayout2_4)
        self.verticalLayout_3.addWidget(self.distributionDefBox_2)
        spacerItem = QtWidgets.QSpacerItem(238, 48, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.widgetWebChart = QtWebEngineWidgets.QWebEngineView(self.layoutWidget)
        self.widgetWebChart.setAutoFillBackground(True)
        self.widgetWebChart.setObjectName("widgetWebChart")
        self.horizontalLayout.addWidget(self.widgetWebChart)
        self.horizontalLayout.setStretch(1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 890, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuAbout.addAction(self.actionAbout)
        self.menuAbout.addAction(self.actionHelp)
        self.menuEdit.addAction(self.actionSettings)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.actionExit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.distributionDefBox.setTitle(_translate("MainWindow", "Distribution Definition"))
        self.labelProb.setText(_translate("MainWindow", "Probability"))
        self.labelValue.setText(_translate("MainWindow", "Value"))
        self.lineEditProb1.setToolTip(_translate("MainWindow", "Enter probability between 0 and 100"))
        self.lineEditProb1.setText(_translate("MainWindow", "90"))
        self.lineEditProb1.setPlaceholderText(_translate("MainWindow", "90"))
        self.labeldots1.setText(_translate("MainWindow", ":"))
        self.lineEditValue1.setToolTip(_translate("MainWindow", "Enter probability associated value"))
        self.lineEditValue1.setText(_translate("MainWindow", "11.667"))
        self.lineEditProb2.setToolTip(_translate("MainWindow", "Enter probability between 0 and 100"))
        self.lineEditProb2.setText(_translate("MainWindow", "10"))
        self.lineEditProb2.setPlaceholderText(_translate("MainWindow", "10"))
        self.labeldots2.setText(_translate("MainWindow", ":"))
        self.lineEditValue2.setToolTip(_translate("MainWindow", "Enter probability associated value"))
        self.lineEditValue2.setText(_translate("MainWindow", "20.55"))
        self.distributionDefBox_2.setTitle(_translate("MainWindow", "Distribution Values"))
        self.labelP90.setText(_translate("MainWindow", "P90"))
        self.labeldotsP90.setText(_translate("MainWindow", ":"))
        self.lineEditP90.setToolTip(_translate("MainWindow", "Enter probability associated value"))
        self.labelP50.setText(_translate("MainWindow", "P50"))
        self.labeldotsP50.setText(_translate("MainWindow", ":"))
        self.lineEditP50.setToolTip(_translate("MainWindow", "Enter probability associated value"))
        self.labelP10.setText(_translate("MainWindow", "P10"))
        self.labeldotsP10.setText(_translate("MainWindow", ":"))
        self.lineEditP10.setToolTip(_translate("MainWindow", "Enter probability associated value"))
        self.lineEditProb2_2.setToolTip(_translate("MainWindow", "Calculate value at probability between 0 and 100"))
        self.lineEditProb2_2.setPlaceholderText(_translate("MainWindow", "PX"))
        self.labeldotsP10_2.setText(_translate("MainWindow", ":"))
        self.lineEditP10_2.setToolTip(_translate("MainWindow", "Enter probability associated value"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAbout.setTitle(_translate("MainWindow", "Help"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))

from PyQt5 import QtWebEngineWidgets
