# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_qtdesigner\tribDialogAbout.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dialogAbout(object):
    def setupUi(self, dialogAbout):
        dialogAbout.setObjectName("dialogAbout")
        dialogAbout.resize(370, 260)
        dialogAbout.setMinimumSize(QtCore.QSize(370, 260))
        dialogAbout.setMaximumSize(QtCore.QSize(370, 260))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/CDFPlot.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dialogAbout.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(dialogAbout)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelTitle = QtWidgets.QLabel(dialogAbout)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.labelTitle.setFont(font)
        self.labelTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.verticalLayout.addWidget(self.labelTitle)
        self.labelDisc = QtWidgets.QLabel(dialogAbout)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.labelDisc.setFont(font)
        self.labelDisc.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDisc.setObjectName("labelDisc")
        self.verticalLayout.addWidget(self.labelDisc)
        self.labelAuthor = QtWidgets.QLabel(dialogAbout)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.labelAuthor.setFont(font)
        self.labelAuthor.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAuthor.setObjectName("labelAuthor")
        self.verticalLayout.addWidget(self.labelAuthor)
        self.labelYear = QtWidgets.QLabel(dialogAbout)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.labelYear.setFont(font)
        self.labelYear.setAlignment(QtCore.Qt.AlignCenter)
        self.labelYear.setObjectName("labelYear")
        self.verticalLayout.addWidget(self.labelYear)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.labelGitHub = QtWidgets.QLabel(dialogAbout)
        self.labelGitHub.setMaximumSize(QtCore.QSize(32, 50))
        self.labelGitHub.setToolTipDuration(2000)
        self.labelGitHub.setInputMethodHints(QtCore.Qt.ImhNone)
        self.labelGitHub.setTextFormat(QtCore.Qt.RichText)
        self.labelGitHub.setPixmap(QtGui.QPixmap("icons/GitHub-Mark-32px.png"))
        self.labelGitHub.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGitHub.setOpenExternalLinks(True)
        self.labelGitHub.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.labelGitHub.setObjectName("labelGitHub")
        self.horizontalLayout_2.addWidget(self.labelGitHub)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.pushButton = QtWidgets.QPushButton(dialogAbout)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 23))
        self.pushButton.setMaximumSize(QtCore.QSize(100, 23))
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)

        self.retranslateUi(dialogAbout)
        self.pushButton.released.connect(dialogAbout.close)
        QtCore.QMetaObject.connectSlotsByName(dialogAbout)

    def retranslateUi(self, dialogAbout):
        _translate = QtCore.QCoreApplication.translate
        dialogAbout.setWindowTitle(_translate("dialogAbout", "Trib- About"))
        self.labelTitle.setText(_translate("dialogAbout", "trib"))
        self.labelDisc.setText(_translate("dialogAbout", "A program to help calculate distribution statistics"))
        self.labelAuthor.setText(_translate("dialogAbout", "Created by: Tony Hallam"))
        self.labelYear.setText(_translate("dialogAbout", "2017"))
        self.labelGitHub.setToolTip(_translate("dialogAbout", "trib GitHub"))
        self.labelGitHub.setText(_translate("dialogAbout", "https://github.com/trhallam/trib"))
        self.pushButton.setText(_translate("dialogAbout", "OK"))

