# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_qtdesigner\tribDesign.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(941, 783)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/CDFPlot.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolTipDuration(2)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tabFixedDist = QtWidgets.QWidget()
        self.tabFixedDist.setAutoFillBackground(True)
        self.tabFixedDist.setObjectName("tabFixedDist")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tabFixedDist)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter = QtWidgets.QSplitter(self.tabFixedDist)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.distributionDefBox = QtWidgets.QGroupBox(self.widget)
        self.distributionDefBox.setMinimumSize(QtCore.QSize(250, 170))
        self.distributionDefBox.setMaximumSize(QtCore.QSize(16777215, 180))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.distributionDefBox.setFont(font)
        self.distributionDefBox.setObjectName("distributionDefBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.distributionDefBox)
        self.gridLayout_4.setContentsMargins(-1, -1, -1, 6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBoxDist = QtWidgets.QComboBox(self.distributionDefBox)
        self.comboBoxDist.setCurrentText("")
        self.comboBoxDist.setObjectName("comboBoxDist")
        self.verticalLayout.addWidget(self.comboBoxDist)
        self.horizontalLayoutLabel = QtWidgets.QHBoxLayout()
        self.horizontalLayoutLabel.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayoutLabel.setObjectName("horizontalLayoutLabel")
        self.labelProb = QtWidgets.QLabel(self.distributionDefBox)
        self.labelProb.setMinimumSize(QtCore.QSize(110, 20))
        self.labelProb.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.labelProb.setFont(font)
        self.labelProb.setAlignment(QtCore.Qt.AlignCenter)
        self.labelProb.setObjectName("labelProb")
        self.horizontalLayoutLabel.addWidget(self.labelProb)
        self.labelValue = QtWidgets.QLabel(self.distributionDefBox)
        self.labelValue.setMinimumSize(QtCore.QSize(110, 20))
        self.labelValue.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.labelValue.setFont(font)
        self.labelValue.setAlignment(QtCore.Qt.AlignCenter)
        self.labelValue.setObjectName("labelValue")
        self.horizontalLayoutLabel.addWidget(self.labelValue)
        self.verticalLayout.addLayout(self.horizontalLayoutLabel)
        self.horizontalLayout1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout1.setObjectName("horizontalLayout1")
        self.lineEditProb1 = QtWidgets.QLineEdit(self.distributionDefBox)
        self.lineEditProb1.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEditProb1.setMaxLength(5)
        self.lineEditProb1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditProb1.setClearButtonEnabled(False)
        self.lineEditProb1.setObjectName("lineEditProb1")
        self.horizontalLayout1.addWidget(self.lineEditProb1)
        self.labeldots1 = QtWidgets.QLabel(self.distributionDefBox)
        self.labeldots1.setMinimumSize(QtCore.QSize(10, 45))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.labeldots1.setFont(font)
        self.labeldots1.setAlignment(QtCore.Qt.AlignCenter)
        self.labeldots1.setObjectName("labeldots1")
        self.horizontalLayout1.addWidget(self.labeldots1)
        self.lineEditValue1 = QtWidgets.QLineEdit(self.distributionDefBox)
        self.lineEditValue1.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEditValue1.setMaxLength(10)
        self.lineEditValue1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditValue1.setPlaceholderText("")
        self.lineEditValue1.setClearButtonEnabled(False)
        self.lineEditValue1.setObjectName("lineEditValue1")
        self.horizontalLayout1.addWidget(self.lineEditValue1)
        self.verticalLayout.addLayout(self.horizontalLayout1)
        self.horizontalLayout2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout2.setObjectName("horizontalLayout2")
        self.lineEditProb2 = QtWidgets.QLineEdit(self.distributionDefBox)
        self.lineEditProb2.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEditProb2.setMaxLength(5)
        self.lineEditProb2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditProb2.setClearButtonEnabled(False)
        self.lineEditProb2.setObjectName("lineEditProb2")
        self.horizontalLayout2.addWidget(self.lineEditProb2)
        self.labeldots2 = QtWidgets.QLabel(self.distributionDefBox)
        self.labeldots2.setMinimumSize(QtCore.QSize(10, 45))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.labeldots2.setFont(font)
        self.labeldots2.setAlignment(QtCore.Qt.AlignCenter)
        self.labeldots2.setObjectName("labeldots2")
        self.horizontalLayout2.addWidget(self.labeldots2)
        self.lineEditValue2 = QtWidgets.QLineEdit(self.distributionDefBox)
        self.lineEditValue2.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEditValue2.setMaxLength(10)
        self.lineEditValue2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditValue2.setPlaceholderText("")
        self.lineEditValue2.setClearButtonEnabled(False)
        self.lineEditValue2.setObjectName("lineEditValue2")
        self.horizontalLayout2.addWidget(self.lineEditValue2)
        self.verticalLayout.addLayout(self.horizontalLayout2)
        self.gridLayout_4.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.distributionDefBox)
        self.distributionValuesGroup = QtWidgets.QGroupBox(self.widget)
        self.distributionValuesGroup.setMinimumSize(QtCore.QSize(250, 250))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.distributionValuesGroup.setFont(font)
        self.distributionValuesGroup.setObjectName("distributionValuesGroup")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.distributionValuesGroup)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tableWidgetDistrValues = QtWidgets.QTableWidget(self.distributionValuesGroup)
        self.tableWidgetDistrValues.setObjectName("tableWidgetDistrValues")
        self.tableWidgetDistrValues.setColumnCount(0)
        self.tableWidgetDistrValues.setRowCount(0)
        self.gridLayout_3.addWidget(self.tableWidgetDistrValues, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.distributionValuesGroup)
        self.widget1 = QtWidgets.QWidget(self.splitter)
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 6, 6, 6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineSplitterFixedDistr = QtWidgets.QFrame(self.widget1)
        self.lineSplitterFixedDistr.setFrameShape(QtWidgets.QFrame.VLine)
        self.lineSplitterFixedDistr.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lineSplitterFixedDistr.setObjectName("lineSplitterFixedDistr")
        self.horizontalLayout.addWidget(self.lineSplitterFixedDistr)
        self.widgetWebChart = QtWebEngineWidgets.QWebEngineView(self.widget1)
        self.widgetWebChart.setMinimumSize(QtCore.QSize(600, 0))
        self.widgetWebChart.setAutoFillBackground(True)
        self.widgetWebChart.setObjectName("widgetWebChart")
        self.horizontalLayout.addWidget(self.widgetWebChart)
        self.gridLayout_2.addWidget(self.splitter, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabFixedDist, "")
        self.tabSetDist = QtWidgets.QWidget()
        self.tabSetDist.setObjectName("tabSetDist")
        self.tabWidget.addTab(self.tabSetDist, "")
        self.tabProbit = QtWidgets.QWidget()
        self.tabProbit.setObjectName("tabProbit")
        self.tabWidget.addTab(self.tabProbit, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 941, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuAbout.addAction(self.actionAbout)
        self.menuAbout.addAction(self.actionHelp)
        self.menuEdit.addAction(self.actionSettings)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.actionExit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Trib"))
        self.distributionDefBox.setTitle(_translate("MainWindow", "Distribution Definition"))
        self.labelProb.setText(_translate("MainWindow", "Probability"))
        self.labelValue.setText(_translate("MainWindow", "Value"))
        self.lineEditProb1.setToolTip(_translate("MainWindow", "Enter probability between 0 and 100"))
        self.lineEditProb1.setText(_translate("MainWindow", "0.9"))
        self.lineEditProb1.setPlaceholderText(_translate("MainWindow", "90"))
        self.labeldots1.setText(_translate("MainWindow", ":"))
        self.lineEditValue1.setToolTip(_translate("MainWindow", "Enter probability associated value"))
        self.lineEditValue1.setText(_translate("MainWindow", "11.667"))
        self.lineEditProb2.setToolTip(_translate("MainWindow", "Enter probability between 0 and 100"))
        self.lineEditProb2.setText(_translate("MainWindow", "0.1"))
        self.lineEditProb2.setPlaceholderText(_translate("MainWindow", "10"))
        self.labeldots2.setText(_translate("MainWindow", ":"))
        self.lineEditValue2.setToolTip(_translate("MainWindow", "Enter probability associated value"))
        self.lineEditValue2.setText(_translate("MainWindow", "20.55"))
        self.distributionValuesGroup.setTitle(_translate("MainWindow", "Distribution Values"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFixedDist), _translate("MainWindow", "Fixed Distribution"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSetDist), _translate("MainWindow", "Set Distribution"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabProbit), _translate("MainWindow", "Probit Plot"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAbout.setTitle(_translate("MainWindow", "Help"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))

from PyQt5 import QtWebEngineWidgets
