# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_qtdesigner\qdesignDialogAbout.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dialogAbout(object):
    def setupUi(self, dialogAbout):
        dialogAbout.setObjectName("dialogAbout")
        dialogAbout.resize(370, 300)
        dialogAbout.setMinimumSize(QtCore.QSize(370, 300))
        dialogAbout.setMaximumSize(QtCore.QSize(370, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/CDFPlot.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dialogAbout.setWindowIcon(icon)
        dialogAbout.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gridLayout = QtWidgets.QGridLayout(dialogAbout)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.labelPicTribLogo = QtWidgets.QLabel(dialogAbout)
        self.labelPicTribLogo.setMinimumSize(QtCore.QSize(100, 100))
        self.labelPicTribLogo.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.labelPicTribLogo.setFont(font)
        self.labelPicTribLogo.setText("")
        self.labelPicTribLogo.setPixmap(QtGui.QPixmap(":/icons/icons/CDFPlotLarge.png"))
        self.labelPicTribLogo.setScaledContents(True)
        self.labelPicTribLogo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelPicTribLogo.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.labelPicTribLogo.setObjectName("labelPicTribLogo")
        self.horizontalLayout_3.addWidget(self.labelPicTribLogo)
        self.labelTitle = QtWidgets.QLabel(dialogAbout)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.labelTitle.setFont(font)
        self.labelTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitle.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.labelTitle.setObjectName("labelTitle")
        self.horizontalLayout_3.addWidget(self.labelTitle)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.labelDisc = QtWidgets.QLabel(dialogAbout)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.labelDisc.setFont(font)
        self.labelDisc.setStyleSheet("")
        self.labelDisc.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDisc.setObjectName("labelDisc")
        self.verticalLayout.addWidget(self.labelDisc)
        self.labelAuthor = QtWidgets.QLabel(dialogAbout)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.labelAuthor.setFont(font)
        self.labelAuthor.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAuthor.setObjectName("labelAuthor")
        self.verticalLayout.addWidget(self.labelAuthor)
        self.labelYear = QtWidgets.QLabel(dialogAbout)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.labelYear.setFont(font)
        self.labelYear.setAlignment(QtCore.Qt.AlignCenter)
        self.labelYear.setObjectName("labelYear")
        self.verticalLayout.addWidget(self.labelYear)
        self.labelYear_2 = QtWidgets.QLabel(dialogAbout)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.labelYear_2.setFont(font)
        self.labelYear_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelYear_2.setObjectName("labelYear_2")
        self.verticalLayout.addWidget(self.labelYear_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pushButtonGitHub = QtWidgets.QPushButton(dialogAbout)
        self.pushButtonGitHub.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButtonGitHub.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButtonGitHub.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonGitHub.setAutoFillBackground(False)
        self.pushButtonGitHub.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/GitHub-Mark-32px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonGitHub.setIcon(icon1)
        self.pushButtonGitHub.setIconSize(QtCore.QSize(50, 50))
        self.pushButtonGitHub.setFlat(True)
        self.pushButtonGitHub.setObjectName("pushButtonGitHub")
        self.horizontalLayout_2.addWidget(self.pushButtonGitHub)
        self.pushButtonLIn = QtWidgets.QPushButton(dialogAbout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonLIn.sizePolicy().hasHeightForWidth())
        self.pushButtonLIn.setSizePolicy(sizePolicy)
        self.pushButtonLIn.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButtonLIn.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButtonLIn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonLIn.setAutoFillBackground(False)
        self.pushButtonLIn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/In-Black-48px-R.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonLIn.setIcon(icon2)
        self.pushButtonLIn.setIconSize(QtCore.QSize(50, 50))
        self.pushButtonLIn.setFlat(True)
        self.pushButtonLIn.setObjectName("pushButtonLIn")
        self.horizontalLayout_2.addWidget(self.pushButtonLIn)
        self.pushButtonIcon8 = QtWidgets.QPushButton(dialogAbout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonIcon8.sizePolicy().hasHeightForWidth())
        self.pushButtonIcon8.setSizePolicy(sizePolicy)
        self.pushButtonIcon8.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButtonIcon8.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButtonIcon8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonIcon8.setAutoFillBackground(False)
        self.pushButtonIcon8.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/Icons8_64px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonIcon8.setIcon(icon3)
        self.pushButtonIcon8.setIconSize(QtCore.QSize(50, 50))
        self.pushButtonIcon8.setFlat(True)
        self.pushButtonIcon8.setObjectName("pushButtonIcon8")
        self.horizontalLayout_2.addWidget(self.pushButtonIcon8)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.pushButton = QtWidgets.QPushButton(dialogAbout)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 23))
        self.pushButton.setMaximumSize(QtCore.QSize(100, 23))
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)

        self.retranslateUi(dialogAbout)
        self.pushButton.released.connect(dialogAbout.close)
        QtCore.QMetaObject.connectSlotsByName(dialogAbout)

    def retranslateUi(self, dialogAbout):
        _translate = QtCore.QCoreApplication.translate
        dialogAbout.setWindowTitle(_translate("dialogAbout", "Trib- About"))
        self.labelTitle.setText(_translate("dialogAbout", "trib"))
        self.labelDisc.setText(_translate("dialogAbout", "A program to help calculate distribution statistics"))
        self.labelAuthor.setText(_translate("dialogAbout", "Created by: Tony Hallam"))
        self.labelYear.setText(_translate("dialogAbout", "2017"))
        self.labelYear_2.setText(_translate("dialogAbout", "Icons by Icon8"))
        self.pushButtonGitHub.setToolTip(_translate("dialogAbout", "Github: https://github.com/trhallam/trib"))
        self.pushButtonLIn.setToolTip(_translate("dialogAbout", "Linked-In: https://www.linkedin.com/in/antonyhallam/"))
        self.pushButtonIcon8.setToolTip(_translate("dialogAbout", "Icon8: https://icons8.com/"))
        self.pushButton.setText(_translate("dialogAbout", "OK"))

import qdesignResource_rc
